In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

In [2]:
#Import the ionoshpere dataset
iono_1 = pd.read_csv('ionoshpere.csv')
#Check dimension
iono_1.shape

(351, 35)

In [3]:
#Describe dataset
print(iono_1.describe())

               a1     a2          a3          a4          a5          a6  \
count  351.000000  351.0  351.000000  351.000000  351.000000  351.000000   
mean     0.891738    0.0    0.641342    0.044372    0.601068    0.115889   
std      0.311155    0.0    0.497708    0.441435    0.519862    0.460810   
min      0.000000    0.0   -1.000000   -1.000000   -1.000000   -1.000000   
25%      1.000000    0.0    0.472135   -0.064735    0.412660   -0.024795   
50%      1.000000    0.0    0.871110    0.016310    0.809200    0.022800   
75%      1.000000    0.0    1.000000    0.194185    1.000000    0.334655   
max      1.000000    0.0    1.000000    1.000000    1.000000    1.000000   

               a7          a8          a9         a10  ...         a25  \
count  351.000000  351.000000  351.000000  351.000000  ...  351.000000   
mean     0.550095    0.119360    0.511848    0.181345  ...    0.396135   
std      0.492654    0.520750    0.507066    0.483851  ...    0.578451   
min     -1.000000  

In [4]:
iono_1.dtypes #Get datatype of features

a1       int64
a2       int64
a3     float64
a4     float64
a5     float64
a6     float64
a7     float64
a8     float64
a9     float64
a10    float64
a11    float64
a12    float64
a13    float64
a14    float64
a15    float64
a16    float64
a17    float64
a18    float64
a19    float64
a20    float64
a21    float64
a22    float64
a23    float64
a24    float64
a25    float64
a26    float64
a27    float64
a28    float64
a29    float64
a30    float64
a31    float64
a32    float64
a33    float64
a34    float64
y       object
dtype: object

In [5]:
#Make a copy of original data
iono_2 = iono_1
#deal with categorical(nominal) variables - The class label ‘y’ 
iono_2['y'] = iono_2['y'].replace({'b': 0, 'g': 1})
# get input data in form of array of just values
iono_array = iono_2.values
print(iono_array)
X = iono_array[:,0:-1] #Omit values of label column "y" for input array
print(X)

[[ 1.       0.       0.99539 ...  0.18641 -0.453    1.     ]
 [ 1.       0.       1.      ... -0.13738 -0.02447  0.     ]
 [ 1.       0.       1.      ...  0.56045 -0.38238  1.     ]
 ...
 [ 1.       0.       0.94701 ...  0.92697 -0.00577  1.     ]
 [ 1.       0.       0.90608 ...  0.87403 -0.16243  1.     ]
 [ 1.       0.       0.8471  ...  0.85764 -0.06151  1.     ]]
[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]


In [6]:
#Apply Kmean clustering
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

#### check how many data samples in each cluster

In [10]:
#Get the lables of the new clusters
kmeans_labels = kmeans.labels_
#Get count of each clusters from K_mean
unique_labels, unique_counts = np.unique(kmeans_labels, return_counts=True)
print("cluster counts", dict(zip(unique_labels, unique_counts)))
#Get count of actual labels
unique_y, counts_y = np.unique(iono_array[:,-1], return_counts=True)
print("y counts", dict(zip(unique_y, counts_y)))

cluster counts {0: 161, 1: 190}
y counts {0.0: 126, 1.0: 225}


In [24]:
y = iono_array[:,-1] #Define y as label from the array of the original dataset
# or kmeans_lables = kmeans.predict(X)
accuracy = accuracy_score(y, kmeans_labels)
print("k means prediction accuracy:", accuracy)
print(confusion_matrix(y, kmeans_labels))

k means prediction accuracy: 0.7122507122507122
[[ 93  33]
 [ 68 157]]
